import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import WalletHeader from "./components/wallet-header.tsx";

//项目生成默认字体配置
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers className="flex flex-col min-h-screen">
          <div>
            {/* 钱包连接的标题头 */}
            <WalletHeader />

            <main className="flex flex-col w-full flex-1 items-center">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
